### ISSUE TITLE
Composer: installation error

### ISSUE THREAD

**Issue by aait** [mageplaza/magento-2-swedish-language-pack#2]
Hello!
I'm tried to install language pack using composer and have error:
composer require mageplaza/magento-2-swedish-language-pack:dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package mageplaza/magento-2-swedish-language-pack could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

It seem package was removed from packagist?

**Comment by davidwindell** [comment]
@imsamthomas can you get this listed on repo.magento.com please?

**Comment by zebeel** [comment]
Hi there, 
We have fixed this. 

Thanks for your report.

**Comment by samnguyen80** [comment]
Hi @davidwindell,

We will think about this.
Because of the language packs update frequently, there are 40+ language packs, it's hard to update.

Any reason we have to list on Marketplace?

**Comment by davidwindell** [comment]
@imsamthomas I noticed the other four packs we use are already repo.magento.com. On packagist would be fine too (so they auto-update without you having to do anything). 

Having to add each repository as a VCS in composer.json (especially if using multiple languages) can really slow down the composer install process.

**Comment by samnguyen80** [comment]
Hi,

Why not using Packagist instead of VCS? It is fast and easy to use, without
editting composer.json file.

Yes it is automatically updating translated strings and helps official
Magento translation project better.

**Comment by davidwindell** [comment]
@imsamthomas packagist is fine, looks like it's on there now. Thanks
